--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket"
Outputs: 
  BucketARN: 
    Value: Bucket.Arn
Parameters: 
  BucketName: 
    Default: Interviewbucket
    Type: String
    AllowedPattern: "^[a-zA-Z0-9]\\S*$"
Resources: 
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      AccessControl: Private
      BucketName: S3BucketName
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
