--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket"
Outputs: 
  BucketARN: 
    Value: Bucket.Arn
Parameters: 
  S3BucketName: 
    Default: Interview~bucket
    Type: String
Resources: 
  Bucket: 
    Properties: 
      AccessControl: Private
      BucketName: S3BucketName
      DeletionPolicy: Retain
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      UpdateReplacePolicy: Retain
    Type: "AWS::S3::Bucket"